/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lexerAndParser_JNI_TestJNI */

#ifndef _Included_com_lexerAndParser_JNI_TestJNI
#define _Included_com_lexerAndParser_JNI_TestJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lexerAndParser_JNI_TestJNI
 * Method:    set
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_lexerAndParser_JNI_TestJNI_set
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_lexerAndParser_JNI_TestJNI
 * Method:    get
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_lexerAndParser_JNI_TestJNI_get
  (JNIEnv *, jobject);

/*
 * Class:     com_lexerAndParser_JNI_TestJNI
 * Method:    scan
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lexerAndParser_JNI_TestJNI_scan
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_lexerAndParser_JNI_TestJNI
 * Method:    parse
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lexerAndParser_JNI_TestJNI_parse
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
